name: Run CI-test

on:
  push:
    branches:
      - '**'  # This will trigger on pushes to any branch
  pull_request:
    branches:
      - '**'  # This will trigger on pull requests to any branch
  schedule:
    # Run every Monday at 6am UTC
    - cron: '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade xraybinaryorbit
        pip install pytest>=6.0 coverage
        pip install -r requirements.txt
        pip install coverage         

    - name: Run tests with coverage
      run: |
        echo "hello"  # Use echo instead of print
        cd test  
        coverage run pytest --cov .

