name: Run CI-test

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    # run every Monday at 6am UTC
    - cron: '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 to avoid Node.js deprecation warnings

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5 for compatibility
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade xraybinaryorbit
        pip install pytest>=6.0 coverage
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        cd test
        coverage run -m pytest --verbose  # Run tests and collect coverage
        coverage xml -o coverage.xml  # Save the coverage report in XML format in 'tests' folder
        coverage html  # Generate HTML coverage report
        coverage report  # Display the coverage report in the console

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4  # Updated to v4 for Node.js 20 compatibility
      with:
        name: pytest-results
        path: test/pytest_results.xml  # Ensure correct path for pytest results in 'tests' folder

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4  # Updated to v4 for Node.js 20 compatibility
      with:
        name: coverage-report
        path: test/coverage.xml  # Upload coverage.xml from 'tests' folder
